### ISSUE TITLE
Add in OAuth example

### ISSUE THREAD

**Issue by jenter** [jenter/js-boilerplate#3]

**Comment by darkcody** [comment]
I'm working on setting up an oauth example for the boilerplate, using the [client credentials grant](https://auth0.com/docs/api-auth/grant/client-credentials) flow. The example could either use the [headless lightning nightly](http://headlessnightlyth3vcdx4ci.devcloud.acquia-sites.com) api, or take an approach similar to the decoupled-js/decoupled-drupal app we setup previously, where it's working with a locally spun up drupal site.

@jenter @danepowell - do either of you have a strong preference which way I set up this example?

**Comment by danepowell** [comment]
Do we need some sort of backend counterpart to this repo that's a sample Drupal application?

We would just want to be very clear that it's a demo, and not a starterkit... but we could provide instructions on how people can spin up their own version.

**Comment by darkcody** [comment]
That's the question, whether or not we want to provide a demo backend or use something external. I'm leaning toward the external option, since the backend isn't useful to the starterkit. Obviously also lower loe since we're using the headless lightning build and not providing the backend ourselves.

**Comment by danepowell** [comment]
Yeah if there's any way we can avoid maintaining yet another Drupal codebase, that would be preferable. Maybe just provide documentation / tutorial on how to spin up a backend based on Lightning nightlies + BLT. It should be pretty straightforward.

**Comment by jenter** [comment]
completed in last iteration with Lightning team
